[package]
name = "hestia-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "*", features = ["quinn","concurrency-limiter","affix-state"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["io"] }
tracing = { version = "*", features = [] }
tracing-subscriber = { version = "*", features = [] }
rcgen = { version = "*", features = [] }
dotenv = { version = "*", features = [] }
serde = { version = "*", features = ["derive"] }
zstd = { version = "*", features = [] }
walkdir = { version = "*", features = [] }
chrono = { version = "*", features = [] }
rayon = { version = "*", features = [] }
astral-tokio-tar = { version = "*", features = [] }
async-compression = { version = "*", features = ["tokio", "zstd"] }
